name: Build AutoFYN Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build EXE and Inno Setup Installer
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --icon=logo.ico RavaDynamics.py

      - name: Create installer using Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" AutoFYN.iss

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: AutoFYN URL Bot Installer
          path: Output/AutoFYN URL Bot Installer.exe
